/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package views;

import controllers.TicketsJpaController;
import daw.Metodos;
import java.math.BigDecimal;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import models.Detalletickets;
import models.Productos;
import models.Tickets;

/**
 *
 * @author clara
 */
public class VentanaDetallesTicket extends java.awt.Dialog {

    /**
     * Creates new form VentanaDetallesTicket
     */
    private static final EntityManagerFactory emf = Persistence.createEntityManagerFactory("daw_dawfoodclarafinal_jar_finalPU");
    private static final TicketsJpaController tjc = new TicketsJpaController(emf);
    private PanelPrincipal panelMain;
    private final Tickets ticket;

    public VentanaDetallesTicket(PanelPrincipal parent, boolean modal, Tickets ticket) {
        super(parent, modal);
        initComponents();
        this.ticket = ticket;
        //cargar los datos del ticket
        mostrarDatosTicket();
        setLocationRelativeTo(panelMain);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDetallesTicket = new javax.swing.JTextArea();
        jBtnVolver = new javax.swing.JButton();

        setResizable(false);
        setTitle("Wok & Roll - Detalle ticket");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jtaDetallesTicket.setEditable(false);
        jtaDetallesTicket.setBackground(new java.awt.Color(204, 204, 204));
        jtaDetallesTicket.setColumns(20);
        jtaDetallesTicket.setForeground(new java.awt.Color(0, 0, 0));
        jtaDetallesTicket.setRows(5);
        jScrollPane1.setViewportView(jtaDetallesTicket);

        jBtnVolver.setBackground(new java.awt.Color(204, 255, 204));
        jBtnVolver.setForeground(new java.awt.Color(0, 0, 0));
        jBtnVolver.setText("VOLVER");
        jBtnVolver.setToolTipText("Volver a la ventana anterior");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jBtnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnVolver)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    //método para cargar los datos del ticket
    private void mostrarDatosTicket() {
        EntityManager em = emf.createEntityManager();
        try {
            tjc.findTickets(ticket.getIdTicket());

            String detalles = "";
            detalles += "================================\n";
            detalles += "\tTICKET DE COMPRA       \n";
            detalles += "\tWok and Roll         \n";
            detalles += "\t"+ticket.getIdTpv().getDireccion()+"           \n";
           detalles += "================================\n";
            detalles += "TPV: "+ticket.getIdTpv().toString()+"           \n";
            detalles += "Número de transacción: " + ticket.getCodTransaccion() + "\n";
            detalles += "================================\n";        
            detalles += "ID del Pedido: " + ticket.getIdTicket() + "\n";
            detalles += "Número de Pedido: " + ticket.getNumeroPedido() + "\n";
            detalles += "Fecha de Emisión: " + Metodos.formatearFecha(ticket.getFechaOperacion()) + "\n";
            detalles += "Hora de Emisión: " + Metodos.formatearHora(ticket.getHoraOperacion()) + "\n";
           detalles += "================================\n";
            detalles += "Productos:\n";

            BigDecimal totalSinIVA = BigDecimal.ZERO;
            BigDecimal totalConIVA = BigDecimal.ZERO;

            for (Detalletickets detalle : ticket.getDetalleticketsCollection()) {
                Productos producto = detalle.getProductos();
                BigDecimal precioSinIVA = producto.getPrecioSinIVA();
                BigDecimal tipoIVA = Metodos.calcularTipoIVA(producto.getTipoIVA());
                BigDecimal precioConIVA = precioSinIVA.add(precioSinIVA.multiply(tipoIVA));
                detalles += "- " + producto.getNombre()
                        + " x " + detalle.getCantidadProducto()
                        + " - " + String.format("%.2f", precioConIVA) + "€\n";
                totalSinIVA = totalSinIVA.add(precioSinIVA.multiply(new BigDecimal(detalle.getCantidadProducto())));
                totalConIVA = totalConIVA.add(precioConIVA.multiply(new BigDecimal(detalle.getCantidadProducto())));
            }

            detalles += "================================\n";
            detalles += "Importe Total sin IVA: " + String.format("%.2f", totalSinIVA) + "€\n";
            detalles += "Importe Total con IVA: " + String.format("%.2f", totalConIVA) + "€\n";
            detalles += "================================\n";

            jtaDetallesTicket.setText(detalles);
        } finally {
            em.close();
        }
    }


    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaDetallesTicket;
    // End of variables declaration//GEN-END:variables
}
